### PR TITLE
Localization should only contain string

### PR DESCRIPTION
**Pull request by nonsensecreativity**
for a better translation, localization should only containing string without the function and processing it separately.

### CODE REVIEW

**Comment by arendjr** [comment]
Thanks, the PR looks good!

But to be honest, I'm not sure yet if this is what I really want... On the one hand it makes the strings easier to translate, but the counter argument is that some flexibility has been lost in the localization. For example, there's no more ability to distinguish between "Enter %s more character to search" and "Enter %s more character**s** to search"...

At least the part where you remove the `<b>` tags from the translatable strings I definitely agree with that's cleaner :)

**Comment by arendjr** [comment]
Could there be a solution that provides best of both worlds? I would prefer a solution where the Ajax module and the Templates module don't need to do any replacements on the strings, and can call the Locale methods like black boxes as before. But inside the Locale module we could have two mappings, one with just strings that are easily translated and one with a combination of strings and methods, like now, but derived from the strings in the first mapping. But to be honest, I don't know if that defeats the purpose of why you wanted this :)

**Comment by nonsensecreativity** [comment]
In my use case: 
The translation is handled via server side script by reading .pot file. By using .pot it's not possible to also have function in the translation line. Currently I'm forcing my selectivity build. still haven't found any other good solution.

**Comment by arendjr** [comment]
Hi again, I appreciate the PR, but I think in its current form it's not entirely what I would like to see (as explained in previous comments) and to be honest I haven't got the time to adjust it myself. So for now I will close it.
Thanks!

**Pull request closed without merging**
