### PR TITLE
Customizable z-index

### PR DESCRIPTION
**Pull request by msx2**
@arendjr By changing default value of `z-index` to `1045` Selectivity.js becomes compatible with Bootstrap modals. And since this value needed change, I figured it's a perfect moment to introduce a new variable. And especially that Foundation uses different defaults than Bootstrap (`1004` for backdrop and `1005` for modal).

### CODE REVIEW

**Comment by iflamed** [comment]
May we need a option to set this z-index from the javascript way. Now you just fixed the bootstrap modal, there may be more framework's modal has a different z-index.

**Comment by msx2** [comment]
There's no framework-independent option really. As I mentioned, Foundation uses different approach - `1004` for backdrop and `1005` for modal. Using e.g. `1000` with Bootstrap we end up with `.modal-backdrop` being above `.selectivity-backdrop`.

JavaScript is not a perfect solution either. It would require assumption that all frameworks use the same naming convention (which they don't, e.g. Foundation uses `.reveal-modal`), or create a complicated regexp-based selector for `.(*-)modal` or something similar. To override those, we would need to use `!important` in the styles layer.

That's why I've used a variable that can be easily modified to create a custom build (or simply overwritten for Sass users), depending on a framework and/or needs :smile:

**Comment by iflamed** [comment]
Yes, you are right. The ``` !important  ``` is enough to override this. And in most project the don't need to create a custom build, override these using the way like ```.selectivity-backdrop { z-index: 1045; }``` .

**Comment by arendjr** [comment]
Good job, guys! Thanks!

**Pull request merged**
