### PR TITLE
Use jQuery.map utility as we can deal with objects instead of arrays only

### PR DESCRIPTION
**Pull request by glafarge**

### CODE REVIEW

**Comment by arendjr** [comment]
Sure thing, can you add a small unit test that shows the functionality? Thanks!

**Comment by glafarge** [comment]
To be honest, i never used unit tests. 
This is a good time to start probably, but i need your help :)
I think I have to implement a new unit test file for ajax, right ?

**Comment by arendjr** [comment]
No problem :)
Yeah, I'd advice to take one of the other test files as a starting point. The README contains instructions on how to run tests (note you can use `--test=...` to run a specific test as well).
I think the one tricky thing about writing AJAX tests is that you don't want to do actual AJAX requests, so I guess you should use the `transport` option to fake the replies from a REST service.
If you have any more questions, just let me know. Cheers!

**Comment by glafarge** [comment]
Thank you for your message. I'll try it with probably some mistakes...

**Comment by glafarge** [comment]
It was hard to understand how to deal with Ajax call. But an interesting first approach to unit testing. 
A lot of things learned. Impatient to get your feedback.

Note : probably not DRY ^^

**Comment by arendjr** [comment]
Well, these are great tests actually! A bit of repetition in test cases is not unexpected, to be honest, so I wouldn't worry too much about that.

The comment about "launch array" I guess shouldn't be in all the cases. As for code style I prefer not to use spaces inside braces (like you do inside the `test.equal()` calls). But these are my only nitpicks :)

Do you want to fix those? Otherwise it's good enough to merge already.

Great job, thanks!

**Comment by glafarge** [comment]
Done ! Thank you for your advices. It helps me to have a new point of view in my coding style (by the way, i never use spaces inside braces habitually).
Now i love unit testing !!

**Comment by arendjr** [comment]
Great to hear :) Cheers!

**Comment by glafarge** [comment]
Cheers!

**Pull request merged**
