### PR TITLE
Append dropdown to body, not after DOM trigger element

### LINKED ISSUE #22: Dropdown positioning in relative container
After the recent changes there's an issue with positioning the dropdown inside relative container, e.g. add the following to one of the `<p>`aragraphs on demo pages that contain selectivity inputs:

```css
width: 50%;
margin: 0 auto;
position: relative;
```

This will result in:
screen shot 2015-04-07 at 22 20 55

I wanted to update `gh-pages` branch to consist the newest build, and saw it happen there.

By the way, @arendjr, is there any way to contact you directly? I tried Twitter, but figured you don't use it on a daily basis :)

### PR DESCRIPTION
**Pull request by msx2**
@arendjr This fixes #22.

Dropdown is appended to the `body`, as it was pre https://github.com/arendjr/selectivity/commit/a6ea06bee24a27d208df12e5b162b74158bb2e3e

_**Note:** That's quite weird so many changes were done by `npm run build` after changing a single line in source..._

### CODE REVIEW

**Comment by arendjr** [comment]
Yes, this is the proper fix indeed. Unfortunately it means I need to find an alternative method to fix tab navigation, but so be it.

PS.: Don't worry about the changes in the dist/ folder. They're because I hadn't created a new build after my last commit, which was for some work I'm doing on keyboard accessibility, but which is not finished yet.

**Comment by msx2** [comment]
@arendjr Now that I come to think of it, this is not the only solution for the positioning problem.

After `addToDom` once more appends element to body and uses body-relative position, this has also a flaw. If you have a dropdown open and decide to resize a viewport manually (resize browser), dropdown will remain in the point that it initially was opened in.

The behaviour could be changed to the following:

1. Change structure for selectivity inputs. I.e. create some `.parent-container` with `position: relative` already set.
2. After dropdown openining event is triggered, script should append the dropdown to `.parent-container` and use position relative to this element.

__Pros:__
- Script becomes fully responsive on its own without any additional JS code (e.g. window resize handler)
- DOM structure and styling does not depend on any non-related DOM element

__Cons:__
- Need to change the current templates and introduce top-level relative parent container

__Pros/cons:__
- Need to change the logic responsible for counting the values to set proper position: or better yet, remove it and set `down: 0` for dropdown that should work out of the box considering it being in the relative contaienr

What to you think?

**Comment by arendjr** [comment]
Actually, I thought of two more cons to adding the dropdown in the middle of the DOM.

- If the Selectivity input is inside a lightbox/modal that has fixed positioning (for example), it might be impossible for the dropdown to be positioned in such a way that it can "pop out" of the lightbox's area as illustrated here, as opposed to one that is appended to the body, which can always lie on top of everything else:
screen shot 2015-04-10 at 10 11 13

- Maybe I'm mistaken, but I think it's gonna be harder to detect whether the dropdown is hitting the bottom of the viewport and should open upwards instead of downwards.

So I think I will stick with appending to the body for now, though I agree we should fix the repositioning on window resize :)

**Comment by msx2** [comment]
I don't think there won't be any problems with `z-index` and popping-out or anything. It would be impossible to access selectivity input from the page below the modal, yes. But child element always takes `z-index` from its parent(s) so it would always be displayed properly above the modal content (well, unless we have some different `absolute` inside `absolute` inside `absolute` inception-thing, then this definitely would be a problem).

As for positioning, yeah, some problems with positioning would exist still if we want to detect whether dropdown should open above or below. But for above it would be `top: -#{$dropdown-height}`, and for opening below, I think `top: $input-height` would suffice (`bottom` was my yesterday's bad idea as it would open it above anyway :disappointed:).

**Comment by arendjr** [comment]
Hm, you might be right. I think it might require some tweaking with fixed positioning of the dropdown (rather than absolute as it uses now) to get the dropdown to behave properly while in the lightbox. At least, I just created a jsfiddle to experiment with it and it appears possible :)

Anyway, might be worth to reconsider how we do this...

**Pull request merged**
